server:
  port: 8088

spring:
  application:
    name: js-agent
  
logging:
  level:
    cn.apmen.jsagent: DEBUG
    reactor.netty: INFO
    org.springframework.web: INFO
    cn.apmen.jsagent.framework: DEBUG
    cn.apmen.jsagent.framework.stream: TRACE
    cn.apmen.jsagent.framework.openaiunified: TRACE

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Agent框架配置
agent:
  llm:
    # 默认模型配置
    default-model: "anthropic.claude-sonnet-4"
    default-temperature: 0.7
    default-max-tokens: 2000
    
    # OpenAI API配置
    openai:
      base-url: "you-openai-api-base-url"
      api-key: "you-api-key"
      timeout: 30s
      
  # 对话配置
  conversation:
    max-history: 10
    default-max-rounds: 5
    
  # 工具配置
  tools:
    enabled: true
    timeout: 10s

